model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['university1652']
  targets: ['university1652']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip','random_erase']
  save_dir: 'log/osnet_x1_0_university1652_softmax_cosinelr_tripletloss'

loss:
  name: 'triplet'
  triplet:
    margin: 0.3

sampler:
  train_sampler: RandomIdentitySampler
  train_sampler_t: RandomIdentitySampler

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  fixbase_epoch: 0 #have to set to 0 for triplet loss, was 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False
